### ISSUE TITLE
Merge server and cli

### ISSUE THREAD

**Issue by ant31** [app-registry/appr-cli#26]
cc @jzelinskie 

I am going to merge the server code and the cli. 
The separation was done to get as few pip dependencies as possible on the cli. 
It is now compiled and it make less sense to have separate repo / source. 

Also I plan to implement logic that could be executed on both server-side and cliient-side (same code)

**Comment by jzelinskie** [comment]
sgtm

**Comment by joejulian** [comment]
I wish you wouldn't. In attempting to keep docker files as small as possible, it's nice to not to have to install the additional server code that won't be used, especially since we have to install from source because the dynamically linked binary won't work on Alpine Linux.

**Comment by ant31** [comment]
@joejulian thanks for your comment. 

Yes the initial goal of the split was to keep the cli with nearly no python dependencies. 
But server isn't using too many libraries, but we can still merge code and have a build that doesn't install the 'server' dependencies.

**Comment by joejulian** [comment]
Fair enough, thanks.

**Comment by ant31** [comment]
I am going to archive this repo, merge is complete. 

@joejulian 
A docker is now build from appr-registry/appr-server using alpine:
https://quay.io/repository/appr/appr?tab=tags
It contains both server/cli and takes ~15MB. 

```
docker run --rm quay.io/appr/appr appr list quay.io -o ant31                                                                                  255 17:43:27
app                      release       downloads    manifests
-----------------------  ------------  -----------  -----------
quay.io/ant31/ghost      0.4.6-1       -            helm
quay.io/ant31/cookieapp  0.13.10       -            helm
quay.io/ant31/etcd       0.2.0         -            helm
quay.io/ant31/cookie     0.13.10       -            helm
quay.io/ant31/kube-lego  0.1.4-1       -            kpm
quay.io/ant31/nginx      0.9.0-beta.3  -            kpm
```

```
docker run -p5000:5000 --rm quay.io/appr/appr run-server                                                                                          17:44:38
Listening 0.0.0.0:5000
--------------------------------------------------------------------------------
INFO in app [appr/api/app.py:28]:
Start service
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in info [appr/api/info.py:23]:
request
--------------------------------------------------------------------------------
172.17.0.1 - - [2017-06-27 15:45:17] "GET /cnr/version HTTP/1.1" 200 166 0.004301
```


The helm plugin and helm-cli isn't included but should be easy to add them from that image
